apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudojoss
  labels:
    app: sudojoss
spec:
  replicas: 1
  selector:
    matchLabels:
     app: sudojoss 
  template:
    metadata:
      labels:
        app: sudojoss
    spec:
      containers:
        - name: sudojoss
          image: jphuc96/sudojoss-landing-page:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: {}